import './test/flat.test';
import './test/difference.test';
import './test/deepClone.test';
import './test/findIndex.test';
import './test/deepEqual.test';
import './test/chunk.test';
import './test/compactFalse.test';
import './test/concat.test';
import './test/generateArr.test';
