
name: jest测试

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: install
      run: |
        echo install dependencies
        yarn

    - name: test
      run: |
        echo start test
        yarn test
